### ISSUE TITLE
Brew installation

### ISSUE THREAD

**Issue by ikost** [JYU-IBA/jabs#5]
Hi, 
is it planned to add the brew installation for the code similar to jibal? 
This can be really helpful for quick update to the new version...
Thanks!
Ilya

**Comment by jaakkojulin** [comment]
I've added JaBS to our [homebrew](https://github.com/JYU-IBA/homebrew-iba) tap, but this is only the command line version. Install with `brew install jabs-cli`. The GUI (QJaBS) I will continue to distribute as a DMG file on Mac, since this is a convenient way to also provide the necessary stopping data for JIBAL etc. This DMG would need ARM-support (Apple silicon), too...

I have been quite lazy with the releases so far, since JaBS is not properly benchmarked and documented. Things are still actively developed, so scripts created today might not be supported tomorrow. By version 1.0 I hope I have things sorted out.

If you have used JaBS for something, I would like to know more details and I would appreciate feedback. You can send an email (you can probably find or guess my email address (....jyu.fi).
